### ISSUE TITLE
Use side margin on body

### ISSUE THREAD

**Issue by Seb33300** [mladenplavsic/bootstrap-navbar-sidebar#5]
Pull request : https://github.com/mladenplavsic/bootstrap-navbar-sidebar/pull/3

As you can see on this plunker: https://plnkr.co/edit/rmFAsEnHkgmnDkTBMw0m?p=preview

If you add a 100% element with an absolute position (green div at the bottom), an horizontal scrollbar appear.

On `body`, if you set:
``` css
body {
  position: relative; 
  padding-left: 0;
  margin-left: 232px;
}
```

Horizontal scrollbar disappear.

Usefull to attach a footer always at the bottom of the page with
``` css
body {
  position: relative;
  min-height: 100%;
}
```

I also don't understand why you applied a 200vh min-height on body by default?
